# gitlab-values.yaml
# Una configuración "ultraligera" de GitLab en Kubernetes.
global:
  edition: ce
  hosts:
    domain: example.com
    https: false
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
registry:
  enabled: false
