# Configuración "mega-ligera" de GitLab en Kubernetes.
# Esta configuración es la que será utilizada por Helm para desplegar GitLab en el cluster de Kubernetes.
global:
  edition: ce                   # Community Edition (evita la versión enterprise)
  hosts:
    domain: localhost
    https: false
  ingress:
    class: traefik              # si no, cada "helm upgrade" vuelve a dejar los Ingress sin clase y GitLab deja de responder
  kas:
    enabled: false               # integración nativa de GitLab con K8s (su propia alternativa a Argo CD); no la usamos, usamos nuestro propio Argo CD
installCertmanager: false
certmanager-issuer:
  email: admin@gitlab.local     # aunque no lo usaremos porque no habilitamos HTTPS, evita un error de TLS al instalar cert-manager
nginx-ingress:
  enabled: false                # suele instalar nginx por defecto. Entra en conflicto con traefik
prometheus:
  install: false                # instala por defecto prometheus, pero no lo necesitamos y son +2 GB RAM
gitlab-runner:
  install: false                # instala por defecto gitlab-runner, pero no lo necesitamos evitamos +1 GB RAM
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
  gitlab-exporter:
    enabled: false               # exporta métricas para Prometheus, que ya tenemos desactivado; sin consumidor no aporta nada
registry:
  enabled: false
