# Esto le dice a Argo CD "oye, mírate este repo de GitHub que ahí hay cosas que quiero despegar"
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iot-app
  namespace: argocd
spec:
  project: default
  source:
    # 🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴
    # CAMBIA LA URL DE ABAJO POR EL REPO DE GITHUB QUE HA CREADO
    # 🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴🔴
    repoURL: 'https://github.com/mikelezc/miguel-iot-argocd'
    # Esta es la rama, si tu repo crea "main" por defecto, pon main, si no, dejalo en master.
    targetRevision: HEAD
    # Dejamos la ruta (.) para que escanee la base de tu repo buscando el deployment.yaml
    path: '.'
  destination:
    server: 'https://kubernetes.default.svc'
    # El destination namespace debe coincidir con el 'dev' de nuestro yaml
    namespace: dev
  syncPolicy:
    # Estas opciones le dicen a ArgoCD que al ver cambios en Github, aplique automáticamente (auto sync).
    automated:
      prune: true     # Borra cosas obsoletas
      selfHeal: true  # Se asegura de reinstalar si borrás algo accidentalmente en el cluster
