apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3 # <-- ¡IMPORTANTE! El Subject pide 3 réplicas para la App 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx-app2
        image: nginx:alpine
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        command:
        - /bin/sh
        - -c
        args:
        - |
          cat <<EOF >/usr/share/nginx/html/index.html
          <h1>app2</h1>
          <p>pod: ${POD_NAME}</p>
          <p>ip: ${POD_IP}</p>
          EOF
          exec nginx -g 'daemon off;'
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app2
