apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-html
data:
  index.html: |
    <h1>app2</h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 3 # <-- ¡IMPORTANTE! El Subject pide 3 réplicas para la App 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: nginx-app2
        image: nginx:alpine
        volumeMounts:
        - name: app2-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app2-vol
        configMap:
          name: app2-html
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app2
