apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-html
data:
  index.html: |
    <h1>app3</h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: nginx-app3
        image: nginx:alpine
        volumeMounts:
        - name: app3-vol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app3-vol
        configMap:
          name: app3-html
---
apiVersion: v1
kind: Service
metadata:
  name: app3
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: app3
