# Este archio es el "Recepcionista". Redirigirá el tráfico según el HOST
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-ingress
spec:
  # Por defecto, si el Ingress recibe una conexión de un host distinto (o no lo conoce)
  # lo mandará a la app3. Esto es el "Otherwise, app3 will be selected by default".
  defaultBackend:
    service:
      name: app3
      port:
        number: 80
  # Y aquí las reglas explícitas para app1 y app2:
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 80
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2
            port:
              number: 80
