Vagrant.configure("2") do |config|
  # ==========================================
  # CONFIGURACIÓN CROSS-PLATFORM (CAMPUS 42 vs MAC M4 USADO PARA DESARROLLO)
  # ==========================================
  if RUBY_PLATFORM =~ /arm64/ || RUBY_PLATFORM =~ /aarch64/ || (RUBY_PLATFORM =~ /darwin/ && `uname -m`.strip == 'arm64')
    config.vm.box = "bento/ubuntu-22.04"
    provider = ENV['VAGRANT_DEFAULT_PROVIDER'] || "vmware_desktop"
  else
    config.vm.box = "bento/ubuntu-22.04"
    provider = "virtualbox"
  end

  # Configuración Global
  config.vm.provider provider do |v|
    if provider == "virtualbox" || provider == "parallels"
      v.memory = 1536
      v.cpus = 1
    elsif provider == "vmware_desktop"
      v.vmx["memsize"] = "1536"
      v.vmx["numvcpus"] = "1"
    end
  end

  # ==========================================
  # MÁQUINA ÚNICA: Server de K3s (mlezcanoS)
  # ==========================================
  config.vm.define "mlezcanoS" do |server|
    server.vm.hostname = "mlezcanoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider provider do |v|
      if provider == "virtualbox" || provider == "parallels"
        v.name = "mlezcanoS_p2"
      elsif provider == "vmware_desktop"
        v.vmx["displayname"] = "mlezcanoS_p2"
      end
    end
    
    server.vm.provision "shell", path: "scripts/server.sh", args: "192.168.56.110"
  end
end
