Vagrant.configure("2") do |config|
  # ==========================================
  # CONFIGURACIÓN CROSS-PLATFORM (LINUX vs MAC M4 USADO PARA DESARROLLO)
  # ==========================================

  # Determinamos la arquitectura del sistema donde se ejecuta:
  if RUBY_PLATFORM =~ /arm64/ || RUBY_PLATFORM =~ /aarch64/ || (RUBY_PLATFORM =~ /darwin/ && `uname -m`.strip == 'arm64') 
	# === MAC APPLE SILICON ===
    config.vm.box = "bento/ubuntu-26.04"
    # Vagrant en Mac M-Series usará Parallels o VMware
    provider = ENV['VAGRANT_DEFAULT_PROVIDER'] || "vmware_desktop"
  else
    # === Intel/Linux ===
    config.vm.box = "bento/ubuntu-26.04"
    provider = "virtualbox"
  end

  # ==========================================
  # CONFIGURACIÓN GLOBAL (Especificaciones de CPU y RAM)
  # ==========================================
  config.vm.provider provider do |v|
    if provider == "virtualbox" || provider == "parallels"
      v.memory = 512
      v.cpus = 1
    elsif provider == "vmware_desktop"
      v.vmx["memsize"] = "512"
      v.vmx["numvcpus"] = "1"
    end
  end

  # ==========================================
  # MÁQUINA 1: Server (Controller)
  # ==========================================
  config.vm.define "mlezcanoS" do |server|
    server.vm.hostname = "mlezcanoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider provider do |v|
      if provider == "virtualbox" || provider == "parallels"
        v.name = "mlezcanoS"
      elsif provider == "vmware_desktop"
        v.vmx["displayname"] = "mlezcanoS"
      end
    end
    
    # Ejecutamos el script cuando se crea la máquina
    server.vm.provision "shell", path: "scripts/server.sh", args: "192.168.56.110"
  end

  # ==========================================
  # MÁQUINA 2: Worker (Agent)
  # ==========================================
  config.vm.define "mlezcanoSW" do |worker|
    worker.vm.hostname = "mlezcanoSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider provider do |v|
      if provider == "virtualbox" || provider == "parallels"
        v.name = "mlezcanoSW"
      elsif provider == "vmware_desktop"
        v.vmx["displayname"] = "mlezcanoSW"
      end
    end
    
    # Ejecutamos el script del worker, pasándole la IP del jefe y la suya propia
    worker.vm.provision "shell", path: "scripts/worker.sh", args: "192.168.56.110 192.168.56.111"
  end
end
