Vagrant.configure("2") do |config|
  # ==========================================
  # CONFIGURACIÓN CROSS-PLATFORM (CAMPUS 42 vs MAC M4 USADO PARA DESARROLLO)
  # ==========================================
  is_arm = RUBY_PLATFORM =~ /arm64/ || RUBY_PLATFORM =~ /aarch64/ || (RUBY_PLATFORM =~ /darwin/ && `uname -m`.strip == 'arm64')
  provider = ENV['VAGRANT_DEFAULT_PROVIDER']

  if provider.nil? || provider.empty?
    provider = is_arm ? "vmware_desktop" : "virtualbox"
  end

  config.vm.box = "bento/ubuntu-22.04"

  # ==========================================
  # CONFIGURACIÓN DE LA MÁQUINA VIRTUAL (MEMORIA, CPU)
  # ==========================================
  config.vm.provider provider do |v|
    if provider == "virtualbox" || provider == "parallels"
      v.memory = 8192
      v.cpus = 3
    elsif provider == "vmware_desktop"	#vmware_desktop: compatible con Mac
      v.vmx["memsize"] = "8192"
      v.vmx["numvcpus"] = "3"
      v.vmx["cpuid.coresPerSocket"] = "1" # Para evitar problemas con VMware, configuramos 1 core por socket.
    end
  end

  # ==========================================
  # CONFIGURACIÓN DE LA MÁQUINA VIRTUAL (HOSTNAME, IP, PORTS)
  # ==========================================
  config.vm.define "mlezcanoS" do |server|
    server.vm.hostname = "mlezcanoS"
    server.vm.network "private_network", ip: "192.168.56.111"
    server.vm.network "forwarded_port", guest: 8888, host: 8889, auto_correct: false
    server.vm.network "forwarded_port", guest: 80, host: 8081, auto_correct: false

    server.vm.provider provider do |v|
      if provider == "virtualbox" || provider == "parallels"
        v.name = "mlezcanoS_bonus"
      elsif provider == "vmware_desktop"
        v.vmx["displayname"] = "mlezcanoS_bonus"
      end
    end
    
    # Instalamos Docker, K3d, GitLab y ArgoCD.
    server.vm.provision "shell", path: "scripts/install.sh", privileged: true
    server.vm.provision "shell", path: "scripts/post-install.sh", privileged: true
  end
end
