Vagrant.configure("2") do |config|
  # ==========================================
  # MAGIA CROSS-PLATFORM (ESCUELA vs MAC M4)
  # ==========================================
  if RUBY_PLATFORM =~ /arm64/ || RUBY_PLATFORM =~ /aarch64/ || (RUBY_PLATFORM =~ /darwin/ && `uname -m`.strip == 'arm64')
    config.vm.box = "bento/ubuntu-22.04"
    provider = ENV['VAGRANT_DEFAULT_PROVIDER'] || "vmware_desktop"
  else
    config.vm.box = "bento/ubuntu-22.04"
    provider = "virtualbox"
  end

  # ==========================================
  # CONFIGURACIÓN (K3D + ArgoCD es pesadito)
  # ==========================================
  config.vm.provider provider do |v|
    if provider == "virtualbox" || provider == "parallels"
      v.memory = 3072 # 3GB RAM para no sufrir con ArgoCD y K3D
      v.cpus = 2
    elsif provider == "vmware_desktop"
      v.vmx["memsize"] = "3072"
      v.vmx["numvcpus"] = "2"
    end
  end

  # ==========================================
  # MÁQUINA DE DESPLIEGUE P3
  # ==========================================
  config.vm.define "mlezcanoS" do |server|
    server.vm.hostname = "mlezcanoS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    # Redirigimos el localhost de la VM al localhost del Mac para cumplir con el tutorial
    server.vm.network "forwarded_port", guest: 8888, host: 8888
    server.vm.network "forwarded_port", guest: 8080, host: 8080
    server.vm.provider provider do |v|
      if provider == "virtualbox" || provider == "parallels"
        v.name = "mlezcanoS_p3"
      elsif provider == "vmware_desktop"
        v.vmx["displayname"] = "mlezcanoS_p3"
      end
    end
    
    # En p3 instalamos K3d y Docker desde el script
    server.vm.provision "shell", path: "scripts/install.sh", privileged: true
  end
end
